### ISSUE TITLE
feature request: search functionality

### ISSUE THREAD

**Issue by max397574** [ghostty-org/website#199] opened 2024-12-28 11:28 UTC
It would help a lot if there would be a search functionality for the documentation. Especially for https://ghostty.org/docs/config/reference.

**Comment by ronanru** [comment] 2024-12-28 14:21
This is a duplicate of #161 

There is a discussion about this feature here - https://github.com/ghostty-org/ghostty/discussions/3195#discussion-7747236

**Closed** 2024-12-28 16:40 UTC
